    [webservices]
    10.14.75.2 ansible_user=root ansible_ssh_private_key_file=/home/maindev/.ssh/wsrootkey
    [omv]
    10.14.75.3 ansible_user=root ansible_ssh_private_key_file=/home/maindev/.ssh/omv_admin_key
    [docker]
    10.14.75.4 ansible_user=maindev ansible_become=true ansible_ssh_private_key_file=/home/maindev/.ssh/docker_admin_key
